name: Build
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to the Registry.
        run : |
          echo $DOCKERHUB_PASSWORD > password.txt
          cat password.txt | docker login -u $DOCKERHUB_USER --password-stdin
      - name: Pack the bundle
        run: cd application && ent bundle pack --org cecchisandrone --stdout
