name: Build
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pack the bundle
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          # Needed to build node-sass
          apk add python3
          cd application 
          ent --debug bundle pack --org cecchisandrone --stdout
          cat $HOME/.docker/config.json
          ent --debug bundle publish
          echo "Published bundle"
