name: Build
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Debug
        run : |
          env
      - name: Login to the registry
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run : |
          echo $REGISTRY_PASSWORD > password.txt
          cat password.txt | docker login -u $REGISTRY_USERNAME --password-stdin
      - name: Pack the bundle
        run: |
          apk add python3 nodejs npm
          npm --version
          node --version
          cd application && ent --debug bundle pack --org cecchisandrone --stdout
          docker images
          ent bundle publish
