name: Build
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pack the application bundle
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          # Needed to build node-sass
          apk add python3
          cd application 
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish
  layout-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^EHUB-[0-9]{3,5} .*$"
          helpMessage: "Example: 'EHUB-123 A change'"
      - name: Pack the layout bundle
        id: pack
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          versionPrefix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
          echo $versionPrefix
          cd content
          version=$(bash ../.github/functions/utils.sh setBundleVersion $versionPrefix-)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Published bundle version: ${{ steps.pack.outputs.VERSION }}"