name: Build
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]
jobs:
  app-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pack the application bundle
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          printenv
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          # Needed to build node-sass
          apk add python3
          cd application 
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish
  layout-build:
    runs-on: ubuntu-latest
    container:
      image: cecchisandrone/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Pack the layout bundle
        env:
          REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          REGISTRY_HOST: registry.hub.docker.com
          DOCKER_ORG: cecchisandrone
        run: |
          docker login $REGISTRY_HOST -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
          cd content 
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish