name: Deploy on EntandoApp

on:
  workflow_call:
    inputs:
      PROFILE_NAME: 
        required: true
        type: string
      ENTANDO_APP_NAME: 
        required: true
        type: string
      ENTANDO_NAMESPACE: 
        required: true
        type: string
      REPOSITORY_NAME:
        required: true
        type: string
    secrets:
       OPENSHIFT_SERVER:
         required: true
       OPENSHIFT_TOKEN:
         required: true
       OPENSHIFT_NAMESPACE:
         required: true

jobs:
  deploy: 
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - uses: redhat-actions/oc-installer@v1
      - name: Cluster Login
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
      - name: Deploy
        run: |
          ent profile new ${{ inputs.PROFILE_NAME }} ${{ inputs.ENTANDO_APP_NAME }} ${{ inputs.ENTANDO_NAMESPACE }}
          ent profile use ${{ inputs.PROFILE_NAME }}
          ent ecr deploy --repo=docker://entando/${{ inputs.entando-hub-application }}
        working-directory: ${{ inputs.WD }}