name: PR workflow
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
env: 
  SKIP_DEPLOY: ${{ vars.SKIP_DEPLOY }}
  PROFILE_NAME: ${{ vars.PROFILE_NAME }}
  ENTANDO_APP_NAME: ${{ vars.ENTANDO_APP_NAME }}
  ENTANDO_NAMESPACE: ${{ vars.ENTANDO_NAMESPACE }}

jobs:
  
  app-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(^EHUB-[0-9]{3,5} .*$|^ENGPM-[0-9]{3,5} .*$)"
          helpMessage: "Example: 'EHUB-123 A change' or 'ENGPM-123 A change'"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pack the application bundle
        id: pack
        env:
          DOCKER_ORG: entando
        run: |
          versionSuffix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
          bash ../.github/functions/utils.sh setBundleVersion -$versionSuffix
          bash ../.github/functions/utils.sh setComponentVersions -$versionSuffix
          ent --debug bundle pack --org $DOCKER_ORG --stdout --fail-fast
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        working-directory: ./application
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Requested publication of version: `${{ steps.pack.outputs.VERSION }}`

  layout-build:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Check PR name
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "(^EHUB-[0-9]{3,5} .*$|^ENGPM-[0-9]{3,5} .*$)"
          helpMessage: "Example: 'EHUB-123 A change' or 'ENGPM-123 A change'"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Pack the layout bundle
        id: pack
        env:
          DOCKER_ORG: entando
        run: |
          versionSuffix=$(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
          bash ../.github/functions/utils.sh setBundleVersion -$versionSuffix
          sh set-bundle-id.sh $DOCKER_ORG
          ent --debug bundle pack --org $DOCKER_ORG --stdout
          ent --debug bundle publish
          version=$(bash ../.github/functions/utils.sh getBundleImage)
          echo "VERSION=$version" >> $GITHUB_OUTPUT
        working-directory: ./content
      - name: Publish artifact version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Requested publication of version: `${{ steps.pack.outputs.VERSION }}`
  
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
     versionSuffix: $(echo "${{ github.event.pull_request.title }}" | awk '{print $1}')
     SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
    secrets:
     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
  app-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: app-build
    if: ${{ env.SKIP_DEPLOY == 'false' }}
    with:
     PROFILE_NAME: ${{ env.PROFILE_NAME }}
     ENTANDO_APP_NAME: ${{ env.ENTANDO_APP_NAME }}
     ENTANDO_NAMESPACE: ${{ env.ENTANDO_NAMESPACE }}
     REPOSITORY_NAME: entando-hub-application
     WD: ./application
    secrets: 
     OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
     OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
     OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}

  layout-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: layout-build
    if: ${{ env.SKIP_DEPLOY == 'false' }}
    with:
      PROFILE_NAME: ${{ env.PROFILE_NAME }}
      ENTANDO_APP_NAME: ${{ env.ENTANDO_APP_NAME }}
      ENTANDO_NAMESPACE: ${{ env.ENTANDO_NAMESPACE }}
      REPOSITORY_NAME: entando-hub-content
      WD: ./content
    secrets: 
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
      OPENSHIFT_NAMESPACE: ${{ secrets.OPENSHIFT_NAMESPACE }}
      